[tool.poetry]
name = "2021"
version = "0.1.0"
description = ""
authors = ["Nicholas Skehin <nicholas@skeh.in>"]

[tool.poetry.dependencies]
python = "3.9"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
